dependencies:
  - name: nodejs
    version: ~1.9.0
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.1.0
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: redis
    version: "5.1.2"
    repository: "@stable"
    condition: redis.enabled
