dependencies:
  - name: nodejs
    version: ~1.10.0
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.1.0
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: redis
    version: 10.6.18
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
