dependencies:
  - name: nodejs
    version: ~1.3.0
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.1.0
    repository: '@hmctspublic'
  - name: redis
    version: "5.1.2"
    repository: "@stable"
