nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 3000
  memoryRequests: 256Mi
  cpuRequests: 0.2
  memoryLimits: 512Mi
  cpuLimits: 1
  environment:
    SESSION_SECRET:
    HTTP_PROTOCOL: http
    S2S_SECRET: ${S2S_SECRET}
    IDAM_ENABLE_STUB: false
    EVIDENCE_UPLOAD_QUESTION_PAGE_OVERRIDE_ALLOWED: true

  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
