infrastructure_env = "preprod"
node_environment = "preprod"
additional_hostname = "sscs-cor.nonprod.platform.hmcts.net"
idam_url = "https://idam-web-public.aat.platform.hmcts.net/foo"
idam_api_url = "https://idam-api.aat.platform.hmcts.net/foo"
idam_enable_stub = "false"
evidence_upload_question_page_enabled = "false"
evidence_upload_question_page_override_allowed = "true"
