infrastructure_env = "preprod"
node_environment = "preprod"
additional_hostname = "sscs-cor.nonprod.platform.hmcts.net"
idam_url = "https://idam-web-public-idam-aat.service.core-compute-idam-aat.internal"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"