infrastructure_env = "preprod"
node_environment = "preprod"
idam_url = "https://idam.preprod.ccidam.reform.hmcts.net"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
idam_enable_stub = "false"
evidence_upload_question_page_enabled = "false"
evidence_upload_question_page_override_allowed = "true"
