infrastructure_env = "preprod"
node_environment = "preprod"
idam_url = "https://sscs-cor-frontend-aat-staging.service.core-compute-aat.internal/idam-stub"
idam_api_url = "https://sscs-cor-frontend-aat-staging.service.core-compute-aat.internal/idam-stub"
idam_enable_stub = "true"
evidence_upload_question_page_enabled = "false"
evidence_upload_question_page_override_allowed = "true"