infrastructure_env = "prod"
node_environment = "prod"
idam_url = "https://hmcts-access.service.gov.uk"
idam_api_url = "https://idam-api.platform.hmcts.net"
evidence_upload_question_page_enabled = "false"
evidence_upload_question_page_override_allowed = "false"
additional_hostname = "58fd15f9-7a11-4de2-8df1-9aef0e807ec2.cloudapp.net"
