infrastructure_env = "prod"
node_environment = "prod"
idam_url = "https://DUMMY"
idam_api_url = "https://DUMMY"
evidence_upload_question_page_enabled = "false"
evidence_upload_question_page_override_allowed = "false"
additional_hostname = "e9eddc0b-bc6c-49bb-b484-e666085025a2.cloudapp.net"
