infrastructure_env = "prod"
node_environment = "prod"
idam_url = "https://hmcts-access.service.gov.uk"
idam_api_url = "https://idam-api.platform.hmcts.net"
evidence_upload_question_page_enabled = "false"
evidence_upload_question_page_override_allowed = "false"
additional_hostname = "e9eddc0b-bc6c-49bb-b484-e666085025a2.cloudapp.net"
https_only_flag = "false"
