infrastructure_env = "preprod"
node_environment = "sandbox"
idam_url = "https://idam-web-public-idam-sandbox.service.core-compute-idam-sandbox.internal"
idam_api_url = "http://idam-api-idam-sandbox.service.core-compute-idam-sandbox.internal/"
idam_enable_stub = "false"
