apiVersion: v2
name: sscs-mya-frontend
home: https://github.com/hmcts/sscs-mya-frontend
version: 0.1.23
description: SSCS MYA FRONTEND
dependencies:
  - name: nodejs
    version: ~2.3.4
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.1.0
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: redis
    version: 10.6.18
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
